[setup]
python_version = "3.12"
postgres_version = "16.dev"
gcc_version = "latest"

[install]
command = "python -m venv --copies ./project && . ./project/Scripts/activate.bat && pip install -r requirements.txt"

[start]
command = ". ./project/Scripts/activate.bat && gunicorn \"gift_shop.wsgi:application\" --bind 0.0.0.0:8000"