[setup
]
python_version = "3.12"
postgres_version = "16.dev"
gcc_version = "latest"

[install
]
command = "python -m venv --copies ./project && . ./project/Scripts/activate && pip install -r requirements.txt"

[start
]
command = ". ./project/Scripts/activate.bat && python gift_shop/manage.py runserver 0.0.0.0:8000"
